[package]
name = "proj"
version = "0.1.0"
authors = ["Drew Fargo <drew.fargo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
savefile = "0.7.4"
savefile-derive = "0.7.4"
colored = "2.0.0"
